USE MASTER 
GO

CREATE DATABASE AUTORLIBRODB
GO

USE AUTORLIBRODB

GO

CREATE TABLE Autor(
	id INT PRIMARY KEY IDENTITY(1,1),
	nombres VARCHAR (120) NOT NULL,
	apellido VARCHAR (120) NOT NULL,
	fecha_reg DATETIME DEFAULT GETDATE()
)
GO


CREATE TABLE Libro(
	id INT PRIMARY KEY IDENTITY(1,1),
	isbn VARCHAR (40) UNIQUE NOT NULL, 
	fecha_reg DATETIME DEFAULT GETDATE(),
	
	titulo VARCHAR (120) NOT NULL,
	
	
	
	
)
GO


CREATE TABLE AutorLibro(
	id INT PRIMARY KEY IDENTITY(1,1),
	autor_fk INT NOT NULL,
	libro_fk INT NOT NULL,
	FOREIGN KEY(autor_fk) REFERENCES Autor(id),
	FOREIGN KEY(libro_fk) REFERENCES Libro(id),
	UNIQUE (autor_fk,libro_fk)
)
GO